version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
      PYTHONPATH: /app
    volumes:
      - .:/app
    command: >
      python -m uvicorn src.main:app
      --host 0.0.0.0
      --port 8000
